repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
    # - id: nbqa-ruff
    #   args: [ --fix, --exit-non-zero-on-fix ]
    - id: nbqa-black
      args: [ --nbqa-shell ]
      additional_dependencies: [jupytext]  # optional, only if you're using Jupytext
    - id: nbqa-pyupgrade
      args: ["--py311-plus"]
